Add support for accounts parameter in StackSet
AdaCore/e3-aws pull request #127
Opened 2022-04-19 07:15 UTC by Nikokrock

2022-04-19 07:45 UTC, pierretr requested changes

2022-04-19 07:45 UTC, pierretr commented on src/e3/aws/troposphere/cloudformation/__init__.py
> +            stack_set_args["StackInstancesGroup"] = cloudformation.StackInstances(
A list of StackInstances is expected here.

2022-04-19 07:45 UTC, pierretr commented on src/e3/aws/troposphere/cloudformation/__init__.py
> +            stack_set_args["StackInstancesGroup"] = cloudformation.StackInstances(
Accounts and OrganizationalUnitIds cannot be both provided to initialize a single StackInstances instance.

2022-04-28 09:43 UTC, Nikokrock commented on src/e3/aws/troposphere/cloudformation/__init__.py
> +            stack_set_args["StackInstancesGroup"] = cloudformation.StackInstances(
fixed

2022-04-28 09:46 UTC, pierretr approved these changes

2022-04-28 09:58 UTC, merged